/**
 * STATIC DEMO MODE (GitHub Pages). There is no backend: GET requests are answered from a
 * recorded snapshot of a SYNTHETIC demo account (apps/web/public/demo-data, generated by
 * `npm run static-demo:snapshot`). Writes are not persisted. No real health data ever
 * passes through this mode – it cannot upload or store anything.
 */
import {
  getBiomarker, normalizeAliasKey,
  type BiomarkerSummary, type Document, type LabReport, type Specialist,
} from '@vitalog/shared';

export const STATIC_DEMO = import.meta.env.VITE_STATIC_DEMO === 'true';
const BASE = import.meta.env.BASE_URL;

type Snapshot = Record<string, unknown>;
let snapshot: Promise<Snapshot> | null = null;
const load = () => (snapshot ??= fetch(`${BASE}demo-data/snapshot.json`).then((r) => r.json() as Promise<Snapshot>));

const SESSION_KEY = 'vl-static-demo';
// Demo is "logged in" by default (deep links work); only an explicit logout hides it
const started = () => { try { return sessionStorage.getItem(SESSION_KEY) !== '0'; } catch { return true; } };

export class StaticDemoError extends Error {
  status = 403;
  code = 'static_demo';
  constructor() {
    super('Това е статична демо версия: промените не се запазват. Пълната версия работи със защитен сървър.');
  }
}

/** Returns the response body, or throws { status, code, message } like the real API. */
export async function staticRequest(method: string, rawUrl: string, body?: unknown): Promise<unknown> {
  const snap = await load();
  const url = new URL(rawUrl, 'http://x');
  const p = url.pathname;
  const q = url.searchParams;
  const me = snap['/api/auth/me'];

  if (p === '/api/auth/me') {
    if (!started()) throw Object.assign(new Error('Не си влязъл.'), { status: 401, code: 'unauthorized' });
    return me;
  }
  if (p === '/api/auth/demo' || p === '/api/auth/login') {
    try { sessionStorage.setItem(SESSION_KEY, '1'); } catch { /* ignore */ }
    return me;
  }
  if (p === '/api/auth/logout') {
    try { sessionStorage.setItem(SESSION_KEY, '0'); } catch { /* ignore */ }
    return { ok: true };
  }

  if (method !== 'GET') {
    // A few harmless interactions are simulated so the main flow can be explored
    if (/^\/api\/jobs\/[^/]+\/confirm$/.test(p)) {
      const reports = (snap['/api/reports?page=1&pageSize=100&sort=newest'] as { items: LabReport[] }).items;
      const n = (body as { candidates?: Array<{ decision: string }> })?.candidates?.filter((c) => c.decision === 'accepted').length ?? 0;
      return { reportId: reports[0]!.id, saved: n };
    }
    if (/^\/api\/documents\/[^/]+\/url$/.test(p)) return { url: `${BASE}demo-data/docs/${p.split('/')[3]}.pdf`, expiresIn: 300 };
    if (p.startsWith('/api/notifications')) return { ok: true };
    throw new StaticDemoError();
  }

  // Exact recorded response
  const exact = snap[p + (url.search || '')] ?? snap[p];
  if (exact !== undefined && !['/api/biomarkers', '/api/reports', '/api/documents'].includes(p)) return exact;

  if (p === '/api/biomarkers') return filterBiomarkers(snap['/api/biomarkers?sort=newest&status=all'] as BiomarkerSummary[], q);
  if (p === '/api/reports') {
    const all = snap['/api/reports?page=1&pageSize=100&sort=newest'] as { items: LabReport[]; laboratories: unknown[] };
    let items = [...all.items];
    const s = q.get('search')?.toLowerCase();
    if (s) items = items.filter((r) => r.title.toLowerCase().includes(s) || r.laboratory?.name.toLowerCase().includes(s));
    if (q.get('laboratoryId')) items = items.filter((r) => r.laboratory?.id === q.get('laboratoryId'));
    if (q.get('from')) items = items.filter((r) => r.collectedAt >= q.get('from')!);
    if (q.get('to')) items = items.filter((r) => r.collectedAt <= q.get('to')!);
    if (q.get('sort') === 'oldest') items.reverse();
    return { items, total: items.length, page: 1, pageSize: 100, laboratories: all.laboratories };
  }
  if (p === '/api/documents') {
    const all = snap['/api/documents?pageSize=100'] as { items: Array<Document & { reportId: string | null }>; counts: unknown };
    let items = all.items;
    if (q.get('category')) items = items.filter((d) => d.category === q.get('category'));
    const s = q.get('search')?.toLowerCase();
    if (s) items = items.filter((d) => d.name.toLowerCase().includes(s));
    return { ...all, items, total: items.length };
  }
  if (p === '/api/search') {
    const needle = (q.get('q') ?? '').toLowerCase();
    const key = normalizeAliasKey(needle);
    const bms = filterBiomarkers(snap['/api/biomarkers?sort=newest&status=all'] as BiomarkerSummary[], new URLSearchParams({ search: needle }));
    const reports = (snap['/api/reports?page=1&pageSize=100&sort=newest'] as { items: LabReport[] }).items.filter((r) => r.title.toLowerCase().includes(needle) || r.laboratory?.name.toLowerCase().includes(needle));
    const docs = (snap['/api/documents?pageSize=100'] as { items: Document[] }).items.filter((d) => d.name.toLowerCase().includes(needle));
    const specs = (snap['/api/specialists'] as Specialist[]).filter((s) => `${s.name} ${s.specialty} ${s.clinic ?? ''}`.toLowerCase().includes(needle));
    return { biomarkers: key ? bms.slice(0, 10) : [], reports: reports.slice(0, 10), documents: docs.slice(0, 10), specialists: specs.slice(0, 10) };
  }
  if (p === '/api/reports/compare') {
    // recorded as older→newer; try the reverse order too
    const alt = snap[`${p}?a=${q.get('b')}&b=${q.get('a')}`];
    if (alt) return alt;
  }
  if (p === '/api/notes') return [];
  throw Object.assign(new Error('Не е налично в статичната демо версия.'), { status: 404, code: 'not_found' });
}

function filterBiomarkers(all: BiomarkerSummary[], q: URLSearchParams): BiomarkerSummary[] {
  let list = [...all];
  const search = q.get('search');
  if (search) {
    const needle = search.toLowerCase();
    const key = normalizeAliasKey(search);
    list = list.filter((s) => {
      const bm = getBiomarker(s.id);
      return [s.name, ...(bm ? [bm.canonicalName, ...bm.aliases] : [])].some((n) => n.toLowerCase().includes(needle) || (key.length >= 2 && normalizeAliasKey(n).includes(key)));
    });
  }
  const category = q.get('category');
  if (category) list = list.filter((s) => s.category === category);
  const status = q.get('status') ?? 'all';
  if (status === 'out_of_range') list = list.filter((s) => s.latest?.status === 'above' || s.latest?.status === 'below');
  else if (status !== 'all') list = list.filter((s) => s.latest?.status === status);
  if (q.get('favorites')) list = list.filter((s) => s.favorite);
  const sort = q.get('sort') ?? 'newest';
  const by: Record<string, (a: BiomarkerSummary, b: BiomarkerSummary) => number> = {
    newest: (a, b) => (b.latest?.date ?? '').localeCompare(a.latest?.date ?? ''),
    oldest: (a, b) => (a.latest?.date ?? '').localeCompare(b.latest?.date ?? ''),
    name: (a, b) => a.name.localeCompare(b.name, 'bg'),
    latest_value: (a, b) => (b.latest?.displayValue ?? -Infinity) - (a.latest?.displayValue ?? -Infinity),
    most_measured: (a, b) => b.count - a.count,
  };
  return list.sort((a, b) => (by[sort] ?? by.newest!)(a, b) || a.name.localeCompare(b.name, 'bg'));
}
